name: Linux CI

on: [push, pull_request]

jobs:
  linux-cmake:
    name: Lin ${{matrix.TrianglePath}} ${{matrix.OS}} ${{matrix.Configuration}}
    strategy:
      fail-fast: false
      matrix:
        OS: [ubuntu-24.04-arm, ubuntu-24.04]
        Configuration: [Debug]
        TrianglePath: [sdl_d3d9_hlsl_triangle, sdl_d3d9_triangle]
    runs-on: ${{matrix.OS}}

    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
        submodules: true
    - name: Install common libs
      run: sudo apt-get update && sudo apt-get install libsdl2-dev ninja-build
    - name: Install libs for DXVK Native build
      run: sudo apt-get install libvulkan-dev glslang-tools meson
    - name: Install libs for VKD3D (when hlsl build)
      if: ${{ matrix.TrianglePath == 'sdl_d3d9_hlsl_triangle' }}
      run: sudo apt-get install libjson-perl libvulkan-dev spirv-headers wine64-tools
    - name: Build
      run: |
        export VCPKG_ROOT=/usr/local/share/vcpkg
        export CC=clang && export CXX=clang++
        ${CXX} --version && cmake --version
        cd ${{matrix.TrianglePath}}
        cmake --preset=VCPKG-${{matrix.Configuration}}
        cmake --build build/VCPKG-${{matrix.Configuration}}
    - name: Check file
      working-directory: ${{matrix.TrianglePath}}/build/VCPKG-${{matrix.Configuration}}/${{matrix.Configuration}}
      run: |
        file ./${{matrix.TrianglePath}}
        ldd ./${{matrix.TrianglePath}}
