name: Linux CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug]
        triangle_path: [sdl_d3d9_triangle, sdl_pure_triangle]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install libs
      run: |
        sudo apt-get update && sudo apt-get install libsdl2-dev libx11-dev libxcb-present-dev libxcb-dri3-dev libxcb-xfixes0-dev libx11-xcb-dev libdrm-dev libd3dadapter9-mesa-dev ninja-build
    - name: Configure with USE_NINE=ON
      run: |
        export CC=gcc && export CXX=g++
        mkdir ${{ matrix.triangle_path }}/build && cd ${{ matrix.triangle_path }}/build
        cmake .. -G Ninja -DUSE_NINE=ON -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
    - name: Build and check file
      working-directory: ${{ matrix.triangle_path }}/build
      run: |
        ninja
        file ./${{ matrix.configuration }}/${{ matrix.triangle_path }}
        ldd ./${{ matrix.configuration }}/${{ matrix.triangle_path }}
