name: Linux CI

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os:
          - runs_on: ubuntu-24.04-arm
            deploy_arg: "aarch64"
          - runs_on: ubuntu-24.04
            deploy_arg: "x86_64"
        configuration: [Debug]
        triangle_path: [sdl_pure_triangle]
        nine: [NOT_USED]
    runs-on: ${{ matrix.os.runs_on }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install common libs
      run: sudo apt-get update && sudo apt-get install libsdl2-dev ninja-build
    - name: Install libs for Gallium Nine build
      if: ${{ matrix.nine == 'ON' }}
      run: sudo apt-get install libx11-dev libxcb-present-dev libxcb-dri3-dev libxcb-xfixes0-dev libx11-xcb-dev libdrm-dev libd3dadapter9-mesa-dev
    - name: Install libs for DXVK Native build
      if: ${{ matrix.nine == 'OFF' }}
      run: sudo apt-get install libvulkan-dev glslang-tools meson
    - name: Install libs for VKD3D (when hlsl build)
      if: ${{ matrix.triangle_path == 'sdl_d3d9_hlsl_triangle' }}
      run: sudo apt-get install libvulkan-dev spirv-headers wine64-tools
    - name: Configure
      run: |
        echo ${{ runner.arch }}
        export CC=gcc && export CXX=g++
        mkdir ${{ matrix.triangle_path }}/build && cd ${{ matrix.triangle_path }}/build
        cmake .. -G Ninja -DUSE_NINE=${{ matrix.nine }} -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
    - name: Build and check file
      working-directory: ${{ matrix.triangle_path }}/build
      run: |
        ninja
        file ./${{ matrix.configuration }}/${{ matrix.triangle_path }}
        ldd ./${{ matrix.configuration }}/${{ matrix.triangle_path }}
