name: Windows CI

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        configuration: [msvc-debug]
        triangle_path: [sdl_d3d9_triangle, sdl_pure_triangle]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Conan
      run: pip install conan==1.59.0
    - name: Configure with CMakeSettings.json and build
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeSettingsJson
        cmakeSettingsJsonPath: '${{ github.workspace }}/${{ matrix.triangle_path }}/CMakeSettings.json'
        useVcpkgToolchainFile: false
        buildDirectory: '${{ github.workspace }}/build'
        configurationRegexFilter: '${{ matrix.configuration }}'
    - name: Check file
      run: |
        dir build\${{ matrix.configuration }}\bin
