name: Windows CI

on: [push, pull_request]

jobs:
  windows-cmake:
    name: Win ${{matrix.TrianglePath}} ${{matrix.Configuration}}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Debug]
        TrianglePath: [sdl_d3d9_hlsl_triangle, sdl_d3d9_triangle, sdl_pure_triangle]
    steps:
    - uses: actions/checkout@main
      with:
        fetch-depth: 0
        submodules: true
    - name: Install common libs
      run: vcpkg install sdl2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Build
      run: |
        $Env:VCPKG_ROOT="C:/vcpkg"
        cd ${{matrix.TrianglePath}}
        cmake --preset=VCPKG-${{matrix.Configuration}}
        cmake --build build/VCPKG-${{matrix.Configuration}}
    - name: Check file
      working-directory: ${{matrix.TrianglePath}}/build/VCPKG-${{matrix.Configuration}}/${{matrix.Configuration}}
      run: |
        dir
